name: Tests

on:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Create gh-pages branch if it doesn't exist
      - name: Create gh-pages branch
        if: success()
        run: |
            git fetch origin
            if ! git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
            else
            git checkout gh-pages
            fi

      # Set up Node
      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: pnpm exec playwright install

      # Run tests
      - name: Run Playwright tests
        run: pnpm test

      # Generate Allure reports
      - name: Generate Allure Report
        if: success()
        run: pnpm run report:generate

      # Upload Allure report as an artifact
      - name: Upload Allure Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # Load test report history
      - name: Load test report history
        if: success()
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Build test report
      - name: Build test report
        if: success()
        uses: simple-elf/allure-report-action@master
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-report

      # Publish Allure report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
